In [4]:
import tabula
df = tabula.read_pdf('Covid_practice_pdf_extract.pdf', pages = 3, lattice = True)[1]

Got stderr: Dec 06, 2020 8:30:40 PM org.apache.pdfbox.pdmodel.font.FileSystemFontProvider loadDiskCache
WARNING: New fonts found, font cache will be re-built
Dec 06, 2020 8:30:40 PM org.apache.pdfbox.pdmodel.font.FileSystemFontProvider <init>
WARNING: Building on-disk font cache, this may take a while
Dec 06, 2020 8:30:40 PM org.apache.pdfbox.pdmodel.font.FileSystemFontProvider <init>
WARNING: Finished building on-disk font cache, found 376 fonts

In [5]:
df.head(10)

,Reporting Country/\rTerritory/Area†,Total\rconfirmed‡\rcases,New\rconfirmed\rcases,Total\rdeaths,New\rdeaths,Transmission\rclassification§,Days since last\rreported case
0,NaN,Total,New,NaN,NaN,NaN,NaN
1,NaN,eporting Country/,Total,New,Transmission,Days since last,NaN
2,NaN,confirmed‡,confirmed,NaN,NaN,NaN,NaN
3,NaN,erritory/Area†,deaths,deaths,classification§,reported case,NaN
4,NaN,cases,cases,NaN,NaN,NaN,NaN
5,NaN,estern Pacific Region,NaN,NaN,NaN,NaN,NaN
6,China,84347,6,4643,0,Clusters of cases,0.0
7,Singapore,14423,799,14,2,Clusters of cases,0.0
8,Japan,13576,191,376,25,Clusters of cases,0.0
9,Republic of Korea,10752,14,244,1,Clusters of cases,0.0

In [6]:
df.columns

Index(['Reporting Country/\rTerritory/Area†', 'Total\rconfirmed‡\rcases',
       'New\rconfirmed\rcases', 'Total\rdeaths', 'New\rdeaths',
       'Transmission\rclassification§', 'Days since last\rreported case'],
      dtype='object')

In [7]:
df.columns = df.columns.str.replace('\r', '')

In [8]:
data = df.dropna()
data.to_excel('covidd=_data.xlsx')

In [9]:
data.head()

,Reporting Country/Territory/Area†,Totalconfirmed‡cases,Newconfirmedcases,Totaldeaths,Newdeaths,Transmissionclassification§,Days since lastreported case
6,China,84347,6,4643,0,Clusters of cases,0.0
7,Singapore,14423,799,14,2,Clusters of cases,0.0
8,Japan,13576,191,376,25,Clusters of cases,0.0
9,Republic of Korea,10752,14,244,1,Clusters of cases,0.0
10,Philippines,7777,198,511,10,Clusters of cases,0.0