In [1]:
import os
import pandas as pd
cwd = os.getcwd() 
files = os.listdir(cwd) 
print(files)

['.ipynb_checkpoints', 'Data Science Final Project.pptx', 'final_project', 'Fragile states index _ The fund for peace.docx', 'fragile_state_index.xlsx', 'fragile_state_index_sort_USA_ET.xlsx', 'fsi-2006.xlsx', 'fsi-2007.xlsx', 'fsi-2008.xlsx', 'fsi-2009.xlsx', 'fsi-2010.xlsx', 'fsi-2011.xlsx', 'fsi-2012.xlsx', 'fsi-2013.xlsx', 'fsi-2014.xlsx', 'fsi-2015.xlsx', 'fsi-2016.xlsx', 'fsi-2017.xlsx', 'fsi-2018.xlsx', 'fsi-2019.xlsx', 'fsi-2020.xlsx', 'merging_fsi_years.ipynb', 'social_cohesion_2020_only.ipynb', 'social_cohesion_2020_Pvalue_added.ipynb', 'social_cohesion_C2.ipynb', 'social_cohesion_C3.ipynb', 'social_cohesion_E2.ipynb', 'social_cohesion_P3.ipynb', '~$Data Science Final Project.pptx']

In [2]:
df = pd.DataFrame()
for file in files:
     if file.endswith('.xlsx'):
        df = df.append(pd.read_excel(file), ignore_index=True) 
        print(file)
#df.head()

fragile_state_index.xlsx
fragile_state_index_sort_USA_ET.xlsx
fsi-2006.xlsx
fsi-2007.xlsx
fsi-2008.xlsx
fsi-2009.xlsx
fsi-2010.xlsx
fsi-2011.xlsx
fsi-2012.xlsx
fsi-2013.xlsx
fsi-2014.xlsx
fsi-2015.xlsx
fsi-2016.xlsx
fsi-2017.xlsx
fsi-2018.xlsx
fsi-2019.xlsx
fsi-2020.xlsx

In [3]:
df

,Unnamed: 0,Country,Year,Rank,Total,C1: Security Apparatus,C2: Factionalized Elites,C3: Group Grievance,E1: Economy,E2: Economic Inequality,E3: Human Flight and Brain Drain,P1: State Legitimacy,P2: Public Services,P3: Human Rights,S1: Demographic Pressures,S2: Refugees and IDPs,X1: External Intervention,Change from Previous Year
0,0.0,Sudan,2006,1st,112.300000,9.8,9.1,9.7,7.50000,9.2,9.1,9.5,9.500000,9.8,9.600000,9.7,9.8,NaN
1,1.0,Congo Democratic Republic,2006,2nd,110.100000,9.8,9.6,9.1,8.10000,9.0,8.0,9.0,9.000000,9.5,9.500000,9.5,10.0,NaN
2,2.0,Cote d'Ivoire,2006,3rd,109.200000,9.8,9.8,9.8,9.00000,8.0,8.5,10.0,8.500000,9.4,8.800000,7.6,10.0,NaN
3,3.0,Iraq,2006,4th,109.000000,9.8,9.7,9.8,8.20000,8.7,9.1,8.5,8.300000,9.7,8.900000,8.3,10.0,NaN
4,4.0,Zimbabwe,2006,5th,108.900000,9.4,8.5,8.5,9.80000,9.2,9.0,8.9,9.500000,9.5,9.700000,8.9,8.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5291,NaN,Iceland,2020-01-01 00:00:00,174th,17.800000,1.0,1.8,0.7,2.80000,1.0,2.2,0.7,0.700000,0.7,1.000000,1.7,3.5,-2.000000
5292,NaN,Denmark,2020-01-01 00:00:00,175th,17.213587,1.6,1.4,4.0,1.30000,0.9,1.6,0.6,0.913587,1.4,1.300000,1.7,0.5,-2.286413
5293,NaN,Switzerland,2020-01-01 00:00:00,176th,17.094086,1.4,1.0,3.0,1.60000,1.5,1.4,0.5,1.052499,1.1,1.241587,2.8,0.5,-1.605914
5294,NaN,Norway,2020-01-01 00:00:00,177th,16.191210,1.8,1.1,3.6,1.69121,0.7,1.0,0.5,1.100000,0.6,0.900000,2.5,0.7,-1.808790
5295,NaN,Finland,2020-01-01 00:00:00,178th,14.626666,2.8,1.4,0.9,2.60000,0.5,1.7,0.6,0.626666,0.5,0.700000,1.6,0.7,-2.273334

In [4]:
df.to_excel('fragile_state_index.xlsx')